### ISSUE TITLE
Live API Endpoints

### ISSUE THREAD

**Issue by jpknoll** [CyberSource/cybersource-flex-samples#11]
When will this API be live/testable?

How does this differ with the VISA Flex implementation?

**Comment by cscybs** [comment]
Hello John,

Thanks for your question. This repository contains the example code that is in working order with VISA Developer Platform, providing you follow all the steps contained here: https://github.com/CyberSource/cybersource-flex-samples/blob/master/java/spring-boot/README.md 
Please note that to use that sample code you have to obtain valid Visa Developer Platform account.
 
Please refer to the Contact US section on the cybersource.com website should you have any further questions in this regard?
 
Kind regards, 
cscybs
