### ISSUE TITLE
Signing

### ISSUE THREAD

**Issue by derekpitt** [CyberSource/cybersource-flex-samples#15]
I want to send a Generate Key request directly to the CyberSource API (example: https://apitest.cybersource.com/flex/v1/keys)

What is the correct procedure for signing that request?

The sample c# code in the repository seems to be out of date, and the Java example is using the VISA api (which I do not want to use)

Thanks!

**Comment by derekpitt** [comment]
Actually, I think I have the correct signing in place now...

I do have another question though,

I am getting `Authentication Failed` Now..  I believe it is because I do not have the correct `keyid`..
How would I get that?

**Comment by rhidianj** [comment]
Hi Derek,

Do you have an account with CyberSource? The keyid is available within the API Keys\Shared Secret Key section of your account, titled: Serial Number.

We'll look to get this updated in the UI to make it clearer.

Thanks,

Rhidian

**Comment by derekpitt** [comment]
Thanks...  I'm still having trouble finding this in the UI.. 

My MID is: slideroom_testin_51396

**Comment by rhidianj** [comment]
Here's a walk through:

![rest credentials - 1](https://user-images.githubusercontent.com/22642242/29453209-b69a1590-8400-11e7-8aae-9acb8e3e226c.png)
![rest credentials - 2](https://user-images.githubusercontent.com/22642242/29453210-b69b3cfe-8400-11e7-8edb-004431dde21b.png)
![rest credentials - 3](https://user-images.githubusercontent.com/22642242/29453207-b6977ede-8400-11e7-8a4f-59d22e2e04d2.png)
![rest credentials - 4](https://user-images.githubusercontent.com/22642242/29453206-b69635d8-8400-11e7-9f5b-4d1fc5922b23.png)
![rest credentials - 5](https://user-images.githubusercontent.com/22642242/29453208-b697e32e-8400-11e7-8ca0-2f60c45b25a2.png)

**Comment by derekpitt** [comment]
@rhidianj this works perfectly!!!

Thank you so much!!

**Comment by speeddragon** [comment]
Did CyberSource change anything ? In my page I only have the following options:

"Simple Order", "SOAP", "SCMP" and "Secure Acceptance". Where is the API Keys ? :\

**Comment by rhidianj** [comment]
@speeddragon Our Flexible Token API is currently in beta. Please [get in touch with CyberSource Customer Support](https://support.cybersource.com/cybskb/index?page=content&id=C529) to get your account enabled. Once enabled, you should be able to see the link to create API Keys.

**Comment by rhidianj** [comment]
@speeddragon This looks like a SOAP Toolkit integration, see pages 13-14 of the [CyberSource SOAP Toolkit Configuration guide](http://apps.cybersource.com/library/documentation/dev_guides/SOAP_Toolkits/SOAP_toolkits.pdf).
